minimumReleaseAge: 1440
minimumReleaseAgeStrict: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  lefthook: true
  sharp: true
